version: '3.8'

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    command: >
      bash -c "
        ollama pull llama3 &&
        ollama pull mistral &&
        ollama pull codellama &&
        ollama pull gemma &&
        ollama pull orca-mini &&
        ollama serve"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - openwebui_data:/app/backend/data
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway

  rag-backend:
    build: ./rag_backend
    container_name: rag_backend
    depends_on:
      - ollama
      - open-webui
    volumes:
      - ./rag_backend:/app
      - ./rag_backend/docs:/app/docs  # Mounts host's docs into container
    env_file:
      - ./rag_backend/.env
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    command: cron -f  # runs cron in foreground (uploads run at 2 AM)

volumes:
  openwebui_data:
  ollama_data: