

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    command: >
      sh -c "
        ollama serve &
        sleep 3 &&
        ollama pull llama3 &&
        ollama pull mistral &&
        ollama pull codellama &&
        wait
      "



  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - openwebui_data:/app/backend/data
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway

  rag-backend:
    build: .
    container_name: rag_backend
    depends_on:
      - ollama
      - open-webui
    volumes:
      - .:/app
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    command: python main.py

volumes:
  openwebui_data:
  ollama_data:
