apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: rag-ollama
    component: ollama
  ports:
  - name: http
    port: 11434
    targetPort: 11434
  type: ClusterIP