apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rag-ollama
      component: backend
  template:
    metadata:
      labels:
        app: rag-ollama
        component: backend
    spec:
      containers:
      - name: backend
        image: rag-backend:latest  # Build and tag your image
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        # Load from ConfigMap
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: API_HOST
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: API_PORT
        - name: OLLAMA_HOST
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: OLLAMA_HOST
        - name: OLLAMA_PORT
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: OLLAMA_PORT
        - name: EMBEDDING_MODEL
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: EMBEDDING_MODEL
        # Load secrets
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: JWT_SECRET_KEY
        volumeMounts:
        - name: raw-docs
          mountPath: /data/raw_docs
        - name: index-data
          mountPath: /data/index
        - name: cache-data
          mountPath: /data/cache
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        readinessProbe:
          httpGet:
            path: /admin/ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /admin/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
      volumes:
      - name: raw-docs
        persistentVolumeClaim:
          claimName: raw-docs-pvc
      - name: index-data
        persistentVolumeClaim:
          claimName: index-pvc
      - name: cache-data
        persistentVolumeClaim:
          claimName: cache-pvc