services:
  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes: [shared_models:/root/.ollama]

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    depends_on: [ollama]
    ports: ["3000:8080"]
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes: [openwebui_data:/app/backend/data]

  financial_advisor:
    build: ./financial_advisor
     context: .
     dockerfile: ./financial_advisor/Dockerfile
    depends_on: [ollama]
    ports: ["8501:8501"]
    volumes: [shared_models:/app/data]

  market_researcher:
    build: ./market_researcher
     context: .
     dockerfile: ./market_researcher/Dockerfile
    depends_on: [ollama]
    ports: ["8502:8501"]
    volumes: [shared_models:/app/data]

  turborag:
    build: ./turborag
      context: .
      dockerfile: ./turborag/Dockerfile
    depends_on: [ollama]
    ports: ["8503:8501"]
    volumes: [shared_models:/app/data]

volumes:
  shared_models:
  openwebui_data: