version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes:
      - shared_models:/root/.ollama
    env_file:
      - .env

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    depends_on: [ollama]
    ports: ["3000:8080"]
    environment:
      - "OLLAMA_BASE_URL=http://ollama:11434"
    volumes:
      - openwebui_data:/app/backend/data
    env_file:
      - .env

  financial_advisor:
    build:
      context: .
      dockerfile: ./financial_advisor/Dockerfile
    depends_on: [ollama]
    ports: ["8501:8501"]
    volumes:
      - shared_models:/app/data
    env_file:
      - .env

  market_researcher:
    build:
      context: .
      dockerfile: ./market_researcher/Dockerfile
    depends_on: [ollama]
    ports: ["8502:8501"]
    volumes:
      - shared_models:/app/data
    env_file:
      - .env

  turborag:
    build:
      context: .
      dockerfile: ./turborag/Dockerfile
    depends_on: [ollama]
    ports: ["8503:8501"]
    volumes:
      - shared_models:/app/data
    env_file:
      - .env

volumes:
  shared_models:
  openwebui_data: