version: '3.8'

services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - openwebui_data:/app/backend/data
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway

  backend:
    build: ./rag_backend
    container_name: rag_backend
    ports:
      - "8501:8501"
    depends_on:
      - open-webui
    volumes:
      - ./rag_backend:/app
    env_file:
      - ./rag_backend/.env
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  openwebui_data:
