version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama


  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - openwebui_data:/app/backend/data
    depends_on:
      - ollama
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway

  backend:
    build: ./rag_backend
    container_name: rag_backend
    ports:
      - "8501:8501"
    depends_on:
      - ollama
      - open-webui
    volumes:
      - ./rag_backend:/app
    env_file:
      - ./rag_backend/.env

volumes:
  ollama_data:
  openwebui_data:
